name: Linux Tests

on:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake
      - name: Configure
        run: cmake -B build
      - name: Build
        run: cmake --build build -j
      - name: Test
        run: |
          cd build
          ctest -L gh --output-on-failure
